Task 1
soulfly2007/tasks pull request #1
Opened 2023-05-23 19:41 UTC by soulfly2007

2023-05-29 16:04 UTC, a-kosak-mbx requested changes

2023-05-29 16:04 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    mask = 0b1 << 31
mask - лишняя временная переменная

2023-05-29 16:04 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    mask = 0b01010101010101010101010101010101
mask - лишняя временная переменная, ну и запись в 16-ричной форме была бы короче.

2023-05-29 16:04 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    return bin(value)[2:].count('0')
Дубликат? Ну и работать не будет.

2023-05-29 16:04 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    return bits_0
Пойдет, но есть способы сделать это быстрее.

2023-05-29 16:04 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    return low if value < low and low <= high else (high if value > high else value)
Сравнения между low и high излишни.

2023-05-29 16:04 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    return low if value < low and low < high else (high if value > high and low > high else value)
Можно использовать уже написанную функцию clamp.

2023-06-06 19:10 UTC, soulfly2007 commented on tasks/task_1.py
> +    mask = 0b1 << 31
Можно сделать так:
return value & (0b1 << 31)
или так:
return value & 0x80000000

2023-06-06 19:11 UTC, soulfly2007 commented on tasks/task_1.py
> +    mask = 0b01010101010101010101010101010101
При использовании 16-ричной формы будет:
return (value & 0x55555555) != 0

2023-06-06 19:11 UTC, soulfly2007 commented on tasks/task_1.py
> +    return bits_0
Можно оставить и это решение.
Можно использовать int.bit_count() для подсчета '1' битов и затем найти количество нулевых битов.

2023-06-06 19:11 UTC, soulfly2007 commented on tasks/task_1.py
> +    return low if value < low and low <= high else (high if value > high else value)
Получится так:
return low if value < low else (high if value > high else value)

2023-06-06 19:11 UTC, soulfly2007 commented on tasks/task_1.py
> +    return low if value < low and low < high else (high if value > high and low > high else value)
С использованием функции clamp результат следующий:
return clamp(value, low, high) if low < high else clamp(value, high, low)

2023-06-07 15:54 UTC, a-kosak-mbx requested changes
Вы не пишите, как можно сделать, а просто внесите исправления и добавьте их в репозиторий. На каждое замечание после его исправления жмите `resolve`.

2023-06-07 15:54 UTC, a-kosak-mbx commented on tasks/task_1.py
> +    mask = 0b1 << 31
Так сделайте :)

2023-06-18 15:53 UTC, a-kosak-mbx approved these changes
Все хорошо, можно мержить.

2023-06-18 15:53 UTC, a-kosak-mbx approved these changes
Все хорошо, можно мержить.

2023-06-23 15:02 UTC, merged